export const ERRORS_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    DELIVERY_NOT_FOUND: "DELIVERY_NOT_FOUND",
    INVALID_ORDER_STATUS: "INVALID_ORDER_STATUS",
    INVALID_DELIVERY_STATUS: "INVALID_DELIVERY_STATUS",
    DRIVER_NOT_AVAILABLE: "DRIVER_NOT_AVAILABLE",
    INVALID_MOCK_AMOUNT: "INVALID_MOCK_AMOUNT",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
};
